fn main() -> Int {
    try f()
}

fn f() -> (ok: Int | err: Char) {
    return .err('d')
}