fn main() -> Int {
    f() catch 0
}

fn f() -> Char!Int {
    try g()
}

fn g() -> ()!Int {
    return .err
}